---
title: "Perm Mortality Data"
author: "Mike McPhee Anderson, FSA"
date: "2024-12-14"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(RPostgreSQL)
library(tidyverse)

```

## Connect to the database

I've imported the [ILEC data](https://www.soa.org/resources/research-reports/2021/2017-mortality-experience/) into my own Postgres database.  

* An alternative is to download the CSV from the ILEC page, and import the CSV into DuckDB. The only thing that would change is the `DBI::dbConnect` statement, as the R code is independent of the underlying database.

```{r}

if (!exists("conn")) {
  conn <- DBI::dbConnect(dbDriver("PostgreSQL"), 
                         dbname = "postgres", 
                         host="postgis", 
                         port=5432, 
                         user="postgres", 
                         password="postgres")
  
  # remove the next line if you are not using postgres, or if it 
  # does not match your database structure
  DBI::dbExecute(conn, "SET SEARCH_PATH='soa'")
}

tbl_ilec <- tbl(conn, "ilec_2009_2018") %>%
  mutate(
    gender = upper(trim(gender)),
    smoker_status =  upper(trim(smoker_status)),
    insurance_plan = upper(trim(insurance_plan)),
    age_basis = upper(trim(age_basis)),
    face_amount_band = upper(trim(face_amount_band)),
    number_of_preferred_classes = upper(trim(number_of_preferred_classes)),
    preferred_class = upper(trim(preferred_class)),
    table_version = "2008 VBT",
    table_name = case_when(
      number_of_preferred_classes == "NA" ~ "LIMITED UNDERWRITING",
      TRUE ~ "PRIMARY"
    )
  ) %>%
  filter(
    number_of_preferred_classes != "4",
    insurance_plan == "PERM",
    smoker_status != "UNKNOWN")

head(tbl_ilec)

```

## Append ultimate mortality

```{r}

tbl_vbt <- tbl(conn, "vbt_tables") %>%
  filter(table_version == "2008 VBT",
         select_period == F,
         issue_age == 0,
         table_name %in% c("PRIMARY", "LIMITED UNDERWRITING"))

tbl_ilec.qx <- tbl_ilec %>%
  left_join(tbl_vbt %>% select(-issue_age), by=c(
    "attained_age" = "attained_age",
    "gender"="gender",
    "smoker_status"="smoker",
    "table_version"="table_version", 
    "table_name"="table_name", 
    "age_basis"="alb_anb"))

```

```{r}

tbl_ilec %>%
  summarise(
    cnt_claims = sum(number_of_deaths)
  )

```


```{r}

tbl_ilec.qx %>%
  filter(!is.na(qx)) %>%
  summarise(
    cnt_claims = sum(number_of_deaths)
  )

```

## Create Extract

```{r}

tbl_ilec.qx %>%
  select(observation_year, preferred_indicator, gender, issue_age, duration,
         attained_age, age_basis, face_amount_band, issue_year, smoker_status,
         number_of_preferred_classes, preferred_class,
         number_of_deaths, death_claim_amount, 
         policies_exposed, amount_exposed, qx) %>%
  collect() %>%
  write_rds("/mnt/data/ilec/perm_extract.rds")

```

```{r}

DBI::dbDisconnect(conn)
rm(conn)

```

